### ISSUE TITLE
Callable API

### ISSUE THREAD

**Issue by bojjenclon** [brehaut/manticore#48]
Have you considered exposing the service via an API? It may help developers of other 13th Age tools if they could generate encounters via your service's logic.

An alternative thought would be to separate the core logic from the UI (core logic in one repo and UI in another with the logic as a submodule) so it would be easier to integrate the encounter generator into other applications.

**Comment by brehaut** [comment]
There is no service. There's no server side component at all. I discovered early on how resource hungry this process can get (we are talking potentially hours of computation and gigs of ram consumed if its left to run unbounded), and I have no desire to babysit a server for a hobby project. The application is purely client side javascript that is driven of static data files. 

Secondly I have zero interest in making my life harder by splitting the project into two repos, or building a dedicated 'library project' that others depend upon. 

The application is already split into a UI portion and an allocator portion (the common library project, and the web worker code to run the generation process). If you application can spin up a web worker, it can use the generator as is.

**Comment by brehaut** [comment]
Relevant links:

 * [common library](https://github.com/brehaut/manticore/tree/master/src/ts/common)
 * [generation worker](https://github.com/brehaut/manticore/blob/master/src/ts/workers/generation-process.ts)
 * [allocator](https://github.com/brehaut/manticore/blob/master/src/ts/workers/libs/allocator.ts) and [overview](https://github.com/brehaut/manticore/wiki/Allocation-algorithm)

[tour of the repo](https://github.com/brehaut/manticore/wiki/Tour-of-the-repository)
