### ISSUE TITLE
Access site currently 403

### ISSUE THREAD

**Issue by Hoplite162** [brehaut/manticore#65]
Hi There,

It appears that the manticore.brehaut.net site is currently 403'd. I'd hate to lose access to such a fantastic 13th Age tool!

I am currently running:
Windows 10 Home
Confirmed issue on both MS Edge and Google Chrome browsers
Expected to access Manticore, instead met with 403 error.

Thank you for creating and managing this incredible resource!

**Comment by brehaut** [comment]
Thanks for raising this. I did a server upgrade recently which has probably caused this. I’ll get it fixed as soon as possible.

**Comment by brehaut** [comment]
I believe this has been resolved. If you can please confirm that you can access it now that would be great.

Because of the way the site used to work, theres potential that the application cache could still be masking the issue so I want to confirm that its all good before I close the issue.

**Comment by Hoplite162** [comment]
Looks like it's working again! Thank you so much!
