### ISSUE TITLE
Error in Encounter Build for Dragons

### ISSUE THREAD

**Issue by NightB1ade** [brehaut/manticore#74]
Dragons do not appear to be being added to encounters.  (Extensive testing not done, but this appears to include the variant classifications, e.g. "white", "red").  Any other selected monsters will appear in the generated encounters, just not dragons, and if only dragons are selected, no encounters are generated.

The console log says that "t is undefined" for the processing.js when running it with dragons selected, but not otherwise.

I've had a manual check of the data in the JSON for all the dragons, and I don't spot any irregularities.  Happy to do any further tests that would help!

**Comment by brehaut** [comment]
Thanks, this does appear to be a regression that crept in at some point.

**Comment by brehaut** [comment]
I believe this has been resolved in the commit [ab5284d](https://github.com/brehaut/manticore/commit/ab5284d7abd20b7b7a5ddc8d328a2ec9a88409cf) against the [manticore-2 branch](https://github.com/brehaut/manticore/tree/manticore-2)
